-- Convert currency fields from Int to Decimal for precise financial calculations

-- User balance and PnL fields
ALTER TABLE "User" ALTER COLUMN "balance" TYPE DECIMAL(19, 2) USING "balance"::DECIMAL(19, 2);
ALTER TABLE "User" ALTER COLUMN "balance" SET DEFAULT 10000.00;
ALTER TABLE "User" ALTER COLUMN "realizedPnL" TYPE DECIMAL(19, 4) USING "realizedPnL"::DECIMAL(19, 4);
ALTER TABLE "User" ALTER COLUMN "realizedPnL" SET DEFAULT 0.0000;
ALTER TABLE "User" ALTER COLUMN "totalVolume" TYPE DECIMAL(19, 2) USING "totalVolume"::DECIMAL(19, 2);
ALTER TABLE "User" ALTER COLUMN "totalVolume" SET DEFAULT 0.00;

-- BalanceLedger fields
ALTER TABLE "BalanceLedger" ALTER COLUMN "delta" TYPE DECIMAL(19, 2) USING "delta"::DECIMAL(19, 2);
ALTER TABLE "BalanceLedger" ALTER COLUMN "balanceBefore" TYPE DECIMAL(19, 2) USING "balanceBefore"::DECIMAL(19, 2);
ALTER TABLE "BalanceLedger" ALTER COLUMN "balanceAfter" TYPE DECIMAL(19, 2) USING "balanceAfter"::DECIMAL(19, 2);

-- UserPnLSnapshot fields
ALTER TABLE "UserPnLSnapshot" ALTER COLUMN "realizedPnL" TYPE DECIMAL(19, 4) USING "realizedPnL"::DECIMAL(19, 4);
ALTER TABLE "UserPnLSnapshot" ALTER COLUMN "unrealizedPnL" TYPE DECIMAL(19, 4) USING "unrealizedPnL"::DECIMAL(19, 4);
ALTER TABLE "UserPnLSnapshot" ALTER COLUMN "totalVolume" TYPE DECIMAL(19, 2) USING "totalVolume"::DECIMAL(19, 2);

-- Market pool and seed fields (already Decimal in schema, ensure consistency)
ALTER TABLE "Market" ALTER COLUMN "seed0" TYPE DECIMAL(19, 2) USING "seed0"::DECIMAL(19, 2);
ALTER TABLE "Market" ALTER COLUMN "seed0" SET DEFAULT 1000.00;
ALTER TABLE "Market" ALTER COLUMN "seed1" TYPE DECIMAL(19, 2) USING "seed1"::DECIMAL(19, 2);
ALTER TABLE "Market" ALTER COLUMN "seed1" SET DEFAULT 1000.00;
ALTER TABLE "Market" ALTER COLUMN "pool0" TYPE DECIMAL(19, 2) USING "pool0"::DECIMAL(19, 2);
ALTER TABLE "Market" ALTER COLUMN "pool0" SET DEFAULT 0.00;
ALTER TABLE "Market" ALTER COLUMN "pool1" TYPE DECIMAL(19, 2) USING "pool1"::DECIMAL(19, 2);
ALTER TABLE "Market" ALTER COLUMN "pool1" SET DEFAULT 0.00;
ALTER TABLE "Market" ALTER COLUMN "k" TYPE DECIMAL(38, 4) USING "k"::DECIMAL(38, 4);
ALTER TABLE "Market" ALTER COLUMN "reserve0" TYPE DECIMAL(19, 2) USING "reserve0"::DECIMAL(19, 2);
ALTER TABLE "Market" ALTER COLUMN "reserve0" SET DEFAULT 1000;
ALTER TABLE "Market" ALTER COLUMN "reserve1" TYPE DECIMAL(19, 2) USING "reserve1"::DECIMAL(19, 2);
ALTER TABLE "Market" ALTER COLUMN "reserve1" SET DEFAULT 1000;

-- PriceSnapshot fields
ALTER TABLE "PriceSnapshot" ALTER COLUMN "price0" TYPE DECIMAL(10, 4) USING "price0"::DECIMAL(10, 4);
ALTER TABLE "PriceSnapshot" ALTER COLUMN "price1" TYPE DECIMAL(10, 4) USING "price1"::DECIMAL(10, 4);
ALTER TABLE "PriceSnapshot" ALTER COLUMN "pool0" TYPE DECIMAL(19, 2) USING "pool0"::DECIMAL(19, 2);
ALTER TABLE "PriceSnapshot" ALTER COLUMN "pool1" TYPE DECIMAL(19, 2) USING "pool1"::DECIMAL(19, 2);

-- Bet fields
ALTER TABLE "Bet" ALTER COLUMN "amount" TYPE DECIMAL(19, 2) USING "amount"::DECIMAL(19, 2);
ALTER TABLE "Bet" ALTER COLUMN "payout" TYPE DECIMAL(19, 2) USING "payout"::DECIMAL(19, 2);
ALTER TABLE "Bet" ALTER COLUMN "pricePerShare" TYPE DECIMAL(10, 4) USING "pricePerShare"::DECIMAL(10, 4);
ALTER TABLE "Bet" ALTER COLUMN "shares" TYPE DECIMAL(19, 4) USING "shares"::DECIMAL(19, 4);

-- Position fields
ALTER TABLE "Position" ALTER COLUMN "amount0" TYPE DECIMAL(19, 2) USING "amount0"::DECIMAL(19, 2);
ALTER TABLE "Position" ALTER COLUMN "amount0" SET DEFAULT 0.00;
ALTER TABLE "Position" ALTER COLUMN "amount1" TYPE DECIMAL(19, 2) USING "amount1"::DECIMAL(19, 2);
ALTER TABLE "Position" ALTER COLUMN "amount1" SET DEFAULT 0.00;
ALTER TABLE "Position" ALTER COLUMN "avgCost0" TYPE DECIMAL(10, 4) USING "avgCost0"::DECIMAL(10, 4);
ALTER TABLE "Position" ALTER COLUMN "avgCost0" SET DEFAULT 0;
ALTER TABLE "Position" ALTER COLUMN "avgCost1" TYPE DECIMAL(10, 4) USING "avgCost1"::DECIMAL(10, 4);
ALTER TABLE "Position" ALTER COLUMN "avgCost1" SET DEFAULT 0;
ALTER TABLE "Position" ALTER COLUMN "shares0" TYPE DECIMAL(19, 4) USING "shares0"::DECIMAL(19, 4);
ALTER TABLE "Position" ALTER COLUMN "shares0" SET DEFAULT 0;
ALTER TABLE "Position" ALTER COLUMN "shares1" TYPE DECIMAL(19, 4) USING "shares1"::DECIMAL(19, 4);
ALTER TABLE "Position" ALTER COLUMN "shares1" SET DEFAULT 0;

-- Add claimedAt field for manual redemption
ALTER TABLE "Position" ADD COLUMN IF NOT EXISTS "claimedAt" TIMESTAMP(3);
